import test, { before, after } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';

const port = 3217;
let child;
before(async () => { child = spawn(process.execPath, ['server/index.js'], { env: { ...process.env, PORT: String(port), CHAT_INSPECTOR_API_KEY: 'test-key', DEFAULT_OWNER_ID: 'test-owner' } }); await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('server timeout')), 3000); child.stdout.on('data', (buf) => { if (buf.toString().includes('listening')) { clearTimeout(timer); resolve(); } }); child.on('error', reject); }); });
after(() => child?.kill());
const request = (path, options = {}) => fetch(`http://127.0.0.1:${port}${path}`, { ...options, headers: { authorization: 'Bearer test-key', 'x-owner-id': 'test-owner', 'content-type': 'application/json', ...(options.headers || {}) } });

test('health is public and reports service status', async () => { const r = await fetch(`http://127.0.0.1:${port}/v1/health`); assert.equal(r.status, 200); assert.equal((await r.json()).ok, true); });
test('dashboard is served by the same API service', async () => { const r = await fetch(`http://127.0.0.1:${port}/`); assert.equal(r.status, 200); assert.match(await r.text(), /Chat-Inspector Dashboard/); });
test('owner scope is required on protected routes', async () => { const r = await fetch(`http://127.0.0.1:${port}/v1/stats`, { headers: { authorization: 'Bearer test-key' } }); assert.equal(r.status, 401); });
test('login returns a session token for valid owner credentials', async () => { const r = await fetch(`http://127.0.0.1:${port}/v1/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ownerId: 'test-owner', apiKey: 'test-key' }) }); const body = await r.json(); assert.equal(r.status, 200); assert.equal(typeof body.token, 'string'); const protectedResponse = await fetch(`http://127.0.0.1:${port}/v1/stats`, { headers: { authorization: `Session ${body.token}` } }); assert.equal(protectedResponse.status, 200); });
test('ingestion validates auth and deduplicates fingerprints', async () => { const record = { fingerprint: 'sha256:test-1', conversationRef: '/messages/t/1', conversationName: 'Neeraj', senderName: 'Neeraj', direction: 'incoming', messageText: 'भाई कहाँ हो?', capturedAt: new Date().toISOString() }; const denied = await fetch(`http://127.0.0.1:${port}/v1/messages/batch`, { method: 'POST', body: JSON.stringify({ messages: [record] }), headers: { 'content-type': 'application/json' } }); assert.equal(denied.status, 401); const first = await request('/v1/messages/batch', { method: 'POST', body: JSON.stringify({ messages: [record] }) }); assert.equal((await first.json()).accepted.length, 1); const second = await request('/v1/messages/batch', { method: 'POST', body: JSON.stringify({ messages: [record] }) }); assert.equal((await second.json()).duplicates.length, 1); });
test('search returns stored message without exposing secrets', async () => { const r = await request('/v1/messages?q=कहाँ'); const body = await r.json(); assert.equal(body.messages.length, 1); assert.equal(body.messages[0].messageText, 'भाई कहाँ हो?'); assert.equal(body.messages[0].apiKey, undefined); });
test('export and analysis are read-only and return structured results', async () => { const csv = await request('/v1/export?format=csv'); assert.equal(csv.status, 200); assert.match(await csv.text(), /conversation,sender,direction/); const analysis = await request('/v1/analysis'); const body = await analysis.json(); assert.equal(body.sentiment, 'neutral'); assert.equal(body.topic, 'family'); });
test('notification and timezone settings can be updated per owner', async () => { const update = await request('/v1/settings', { method: 'PUT', body: JSON.stringify({ telegramNotifications: true, timezone: 'Asia/Kolkata' }) }); assert.equal(update.status, 200); const body = await update.json(); assert.equal(body.telegramNotifications, true); const read = await request('/v1/settings'); assert.equal((await read.json()).timezone, 'Asia/Kolkata'); });
test('backup retains deleted status and attachment metadata', async () => { const record = { fingerprint: 'sha256:deleted-1', conversationRef: '/messages/t/2', conversationName: 'Amit', senderName: 'Amit', direction: 'incoming', messageText: '[message unavailable]', capturedAt: new Date().toISOString(), deletedStatus: 'source_deleted', attachments: [{ type: 'image', name: 'photo' }] }; const r = await request('/v1/messages/batch', { method: 'POST', body: JSON.stringify({ messages: [record] }) }); assert.equal((await r.json()).accepted.length, 1); const result = await request('/v1/messages?q=unavailable'); const saved = (await result.json()).messages[0]; assert.equal(saved.deletedStatus, 'source_deleted'); assert.equal(saved.attachments[0].type, 'image'); });
test('semantic search expands Hindi and English intent terms', async () => { await request('/v1/messages/batch', { method: 'POST', body: JSON.stringify({ messages: [{ fingerprint: 'sha256:money-1', conversationRef: '/messages/t/3', conversationName: 'Rahul', senderName: 'Rahul', direction: 'incoming', messageText: 'पैसे कल भेज दूँगा', capturedAt: new Date().toISOString() }] }) }); const result = await request('/v1/semantic-search?q=money'); const body = await result.json(); assert.equal(body.messages[0].messageText, 'पैसे कल भेज दूँगा'); });
