import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRepository } from './repository.js';
import { startTelegramPolling, notifyTelegram } from './telegram.js';
import { login, logout, sessionOwner } from './auth.js';

const PORT = Number(process.env.PORT || 3000);
const API_KEY = process.env.CHAT_INSPECTOR_API_KEY || '';
const OWNER_ID = process.env.DEFAULT_OWNER_ID || '';
const MAX_BATCH = 100;
const rate = new Map();
const settings = new Map();
const json = (res, status, body) => { const payload = JSON.stringify(body); res.writeHead(status, { 'content-type': 'application/json', 'cache-control': 'no-store' }); res.end(payload); };
const readBody = (req) => new Promise((resolve, reject) => { let data = ''; req.on('data', (chunk) => { data += chunk; if (data.length > 2_000_000) reject(new Error('payload too large')); }); req.on('end', () => { try { resolve(JSON.parse(data || '{}')); } catch { reject(new Error('invalid json')); } }); req.on('error', reject); });
const validRecord = (r) => r && typeof r === 'object' && typeof r.fingerprint === 'string' && r.fingerprint.length <= 100 && typeof r.messageText === 'string' && r.messageText.length <= 10000 && ['incoming', 'outgoing', 'unknown'].includes(r.direction) && typeof r.conversationRef === 'string' && r.conversationRef.length <= 500;
const audit = (event, meta = {}) => console.info(JSON.stringify({ event, at: new Date().toISOString(), ...meta }));
const allowed = (req) => { if (API_KEY && req.headers.authorization !== `Bearer ${API_KEY}`) return false; if (OWNER_ID && req.headers['x-owner-id'] !== OWNER_ID) return false; return true; };
const sessionFrom = (req) => { const value = String(req.headers.authorization || ''); return value.startsWith('Session ') ? sessionOwner(value.slice(8)) : null; };
const withinRate = (req) => { const ip = req.socket.remoteAddress || 'unknown'; const now = Date.now(); const item = rate.get(ip) || { at: now, count: 0 }; if (now - item.at > 60000) { item.at = now; item.count = 0; } item.count++; rate.set(ip, item); return item.count <= Number(process.env.RATE_LIMIT_PER_MINUTE || 120); };
const analysis = (items) => { const text = items.map((m) => m.messageText).join(' ').toLowerCase(); const positive = (text.match(/good|great|thanks|love|happy|अच्छा|धन्यवाद|खुश/g) || []).length; const negative = (text.match(/bad|angry|sad|problem|hate|बुरा|गुस्सा|परेशान/g) || []).length; const sentiment = positive > negative ? 'positive' : negative > positive ? 'negative' : 'neutral'; const topic = /money|पैसे|payment|भुगतान/.test(text) ? 'finance' : /work|काम|office|project/.test(text) ? 'work' : /family|घर|भाई|बहन/.test(text) ? 'family' : 'general'; return { summary: `${items.length} backed-up messages analyzed. Dominant topic: ${topic}.`, sentiment, topic, importantMessages: items.filter((m) => /urgent|important|जरूरी|तुरंत/i.test(m.messageText)).slice(0, 10).map((m) => m.fingerprint) }; };
const csv = (items) => ['conversation,sender,direction,message,capturedAt,fingerprint', ...items.map((m) => [m.conversationName, m.senderName, m.direction, m.messageText, m.capturedAt, m.fingerprint].map((v) => `"${String(v || '').replaceAll('"', '""')}"`).join(','))].join('\n');
const semanticTerms = (q) => { const raw = String(q || '').toLowerCase(); const groups = [['money','पैसे','payment','भुगतान','salary','वेतन'],['family','घर','भाई','बहन','माँ','पिता'],['work','काम','office','project','job','नौकरी'],['urgent','जरूरी','तुरंत','important','急']]; return [...new Set([raw, ...groups.filter((g) => g.some((term) => raw.includes(term))).flat()])].filter(Boolean); };
const semanticRank = (items, q) => { const terms = semanticTerms(q); return items.map((m) => ({ m, score: terms.reduce((n, term) => n + (`${m.messageText} ${m.conversationName}`.toLowerCase().includes(term) ? 1 : 0), 0) })).filter((x) => x.score > 0).sort((a, b) => b.score - a.score || b.m.capturedAt.localeCompare(a.m.capturedAt)).map((x) => x.m); };
const ROOT = path.dirname(fileURLToPath(import.meta.url));
const staticFiles = { '/': 'dashboard/index.html', '/index.html': 'dashboard/index.html', '/style.css': 'dashboard/style.css', '/app.js': 'dashboard/app.js', '/analysis.js': 'dashboard/analysis.js' };
const serveStatic = (url, res) => { const relative = staticFiles[url]; if (!relative) return false; const file = path.join(ROOT, '..', relative); if (!fs.existsSync(file)) return false; const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' }; res.writeHead(200, { 'content-type': types[path.extname(file)] || 'application/octet-stream' }); res.end(fs.readFileSync(file)); return true; };
const start = async () => { const repo = await createRepository(); const route = async (req, res) => { const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`); if (req.method === 'GET' && serveStatic(url.pathname, res)) return; if (req.method === 'GET' && url.pathname === '/v1/health') return json(res, 200, { ok: await repo.health(), service: 'chat-inspector-api', storage: repo.mode }); if (!withinRate(req)) return json(res, 429, { error: 'rate_limit_exceeded' }); if (req.method === 'POST' && url.pathname === '/v1/auth/login') { try { const body = await readBody(req); const result = login(String(body.ownerId || ''), String(body.apiKey || ''), OWNER_ID, API_KEY); return result ? json(res, 200, result) : json(res, 401, { error: 'invalid_credentials' }); } catch { return json(res, 400, { error: 'invalid_json' }); } } if (req.method === 'POST' && url.pathname === '/v1/auth/logout') { const token = String(req.headers.authorization || '').replace(/^Session\s+/, ''); logout(token); return json(res, 200, { ok: true }); } const sessionOwnerId = sessionFrom(req); if (!sessionOwnerId && !allowed(req)) return json(res, 401, { error: 'unauthorized' }); if (req.method === 'POST' && url.pathname === '/v1/messages/batch') { try { const body = await readBody(req); if (!Array.isArray(body.messages) || body.messages.length > MAX_BATCH) return json(res, 400, { error: 'messages must be an array of at most 100 records' }); const valid = body.messages.filter(validRecord); const result = await repo.insertBatch(valid.map((r) => ({ ...r, ownerId: sessionOwnerId || req.headers['x-owner-id'] || OWNER_ID || 'owner' }))); result.rejected = body.messages.filter((r) => !validRecord(r)).map((r) => ({ fingerprint: r?.fingerprint || null, reason: 'invalid_record' })); if (settings.get(sessionOwnerId || req.headers['x-owner-id'] || OWNER_ID || 'owner')?.telegramNotifications) await Promise.all(valid.filter((r) => result.accepted.includes(r.fingerprint)).map((r) => notifyTelegram(r))); audit('batch_processed', { accepted: result.accepted.length, duplicates: result.duplicates.length, rejected: result.rejected.length }); return json(res, 200, result); } catch (error) { return json(res, 400, { error: error.message }); } }
    const owner = sessionOwnerId || req.headers['x-owner-id'] || OWNER_ID || 'owner'; if (req.method === 'GET' && url.pathname === '/v1/settings') return json(res, 200, settings.get(owner) || { telegramNotifications: false, timezone: process.env.DEFAULT_TIMEZONE || 'Asia/Kolkata' }); if (req.method === 'PUT' && url.pathname === '/v1/settings') { const body = await readBody(req); const next = { telegramNotifications: Boolean(body.telegramNotifications), timezone: typeof body.timezone === 'string' && body.timezone.length < 80 ? body.timezone : 'Asia/Kolkata' }; settings.set(owner, next); return json(res, 200, next); }
    const filters = Object.fromEntries(url.searchParams); if (req.method === 'GET' && url.pathname === '/v1/semantic-search') return json(res, 200, { query: filters.q || '', messages: semanticRank(await repo.messages({ limit: 500 }), filters.q || '') }); if (req.method === 'GET' && url.pathname === '/v1/messages') return json(res, 200, { messages: await repo.messages(filters) }); if (req.method === 'GET' && url.pathname === '/v1/conversations') return json(res, 200, { conversations: await repo.conversations() }); if (req.method === 'GET' && url.pathname === '/v1/stats') return json(res, 200, await repo.stats()); if (req.method === 'GET' && url.pathname === '/v1/export') { const items = await repo.messages(filters); const format = url.searchParams.get('format') || 'json'; if (format === 'csv') { res.writeHead(200, { 'content-type': 'text/csv', 'content-disposition': 'attachment; filename="chat-inspector-export.csv"' }); return res.end(csv(items)); } if (format === 'txt') { res.writeHead(200, { 'content-type': 'text/plain', 'content-disposition': 'attachment; filename="chat-inspector-export.txt"' }); return res.end(items.map((m) => `[${m.capturedAt}] ${m.conversationName} / ${m.senderName}: ${m.messageText}`).join('\n')); } return json(res, 200, { exportedAt: new Date().toISOString(), messages: items }); } if (req.method === 'GET' && url.pathname === '/v1/analysis') return json(res, 200, analysis(await repo.messages(filters))); return json(res, 404, { error: 'not_found' }); };
    const server = http.createServer((req, res) => route(req, res).catch((error) => { audit('request_failed', { error: error.message }); json(res, 500, { error: 'internal_error' }); })); server.listen(PORT, '0.0.0.0', () => { console.log(`Chat-Inspector API listening on ${PORT} (${repo.mode})`); startTelegramPolling(async () => ({ messages: await repo.messages({ limit: 100 }), conversations: await repo.conversations() })); });
  };
start();
